version: 2.1
jobs:
  build:
    docker:
      - image: hdrjt/aosp:latest
    steps:
      - run: git config --global user.name "nadinsylaa"
      - run: git config --global user.email "asepmlnaaa@gmail.com"
      - run: git clone --depth 1 "https://github.com/nadinsylaa/Styrofoam" --branch "$CIRCLE_BRANCH" .
